# Generated by Django 5.0.14 on 2025-07-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alemdasala", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="humor",
            name="tipo",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="humor",
            name="nivel",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
