# Generated by Django 5.0.14 on 2025-07-07 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alemdasala", "0006_disponibilidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="hora",
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
    ]
